
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlinx.serialization)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation("org.slf4j:slf4j-nop:2.1.0-alpha1")

    implementation("net.java.dev.jna:jna:5.17.0")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    runtimeOnly("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.10.2")
    //IDK why it defaults to runtime only

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")

    implementation(platform("com.squareup.okhttp3:okhttp-bom:5.1.0"))

    // define any required OkHttp artifacts without version
    implementation("com.squareup.okhttp3:okhttp")

    implementation("com.formdev:flatlaf-fonts-jetbrains-mono:2.304")
    implementation("com.formdev:flatlaf-extras:3.6.1")
    implementation("com.github.weisj:jsvg:2.0.0")
    implementation("com.formdev:flatlaf:3.6.1")

    implementation("io.github.dj-raven:modal-dialog:2.5.1")

    implementation("org.openani.jsystemthemedetector:jSystemThemeDetector:3.8")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.2.20-Beta2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

application {
    // Define the main class for the application.
//    mainClass = "org.example.AppKt"
    mainClass.set("us.wprust.jvm.Main")
}

// Helper function to find the correct native library path for the current OS
//fun getJnaPath(): String {
//    val nativeDir = "src/main/resources/natives"
//    val osArch = System.getProperty("os.arch")
//    return when {
//        Os.isFamily(Os.FAMILY_WINDOWS) && osArch == "amd64" -> "$nativeDir/windows-x86_64"
//        Os.isFamily(Os.FAMILY_UNIX) && System.getProperty("os.name")
//            .contains("Linux") && osArch == "amd64" -> "$nativeDir/linux-x86_64"
//
//        Os.isFamily(Os.FAMILY_MAC) && osArch == "aarch64" -> "$nativeDir/macos-aarch64"
//        else -> "" // No specific path for unknown OS
//    }
//}

// Configure tasks that run on the JVM
tasks.withType<JavaExec> {
    jvmArgs("--enable-native-access=ALL-UNNAMED")

    // Dynamically set the jna.library.path based on the current OS
//    val jnaPath = getJnaPath()
//    if (jnaPath.isNotBlank()) {
//        systemProperty("jna.library.path", file(jnaPath).absolutePath)
//    }
}

// Configure test tasks specifically
tasks.withType<Test> {
    jvmArgs("--enable-native-access=ALL-UNNAMED")

    // Also set the path for tests
//    val jnaPath = getJnaPath()
//    if (jnaPath.isNotBlank()) {
//        systemProperty("jna.library.path", file(jnaPath).absolutePath)
//    }
}

// Define a common configuration block for all JAR tasks to avoid repetition
val fatJarConfig: Jar.() -> Unit = {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
            "Main-Class" to application.mainClass.get()
        )
    }

    // --- THIS IS THE CRUCIAL ADDITION ---
    // 1. Add your application's own compiled .class files and resources.
    from(sourceSets.main.get().output)

    // 2. Add all runtime dependencies (unpacks their JARs).
    from({
        configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }
    })
}

// Disable the default 'jar' task to avoid confusion
tasks.jar {
    enabled = false
}

// Task to build the JAR for Windows
tasks.register<Jar>("jarWindows") {
    apply(fatJarConfig) // This will include all 3 native files at first
    group = "build"
    description = "Builds the JAR with the Windows x86_64 native library."
    archiveAppendix.set("windows-x86_64")

    // Now, remove the ones we don't want for Windows
    exclude("libuniffi_wp_epub_mini.so")
    exclude("libuniffi_wp_epub_mini.dylib") // <-- Use your actual macOS library name
}

// Task to build the JAR for Linux
tasks.register<Jar>("jarLinux") {
    apply(fatJarConfig)
    group = "build"
    description = "Builds the JAR with the Linux x86_64 native library."
    archiveAppendix.set("linux-x86_64")

    // Remove the ones we don't want for Linux
    exclude("uniffi_wp_epub_mini.dll")
    exclude("libuniffi_wp_epub_mini.dylib") // <-- Use your actual macOS library name
}

// Task to build the JAR for macOS
tasks.register<Jar>("jarMacos") {
    apply(fatJarConfig)
    group = "build"
    description = "Builds the JAR with the macOS aarch64 native library."
    archiveAppendix.set("macos-aarch64")

    // Remove the ones we don't want for macOS
    exclude("uniffi_wp_epub_mini.dll")
    exclude("libuniffi_wp_epub_mini.so")
}

// A convenient task to build all platform-specific JARs at once
tasks.register("jarAll") {
    group = "build"
    description = "Builds JARs for all supported desktop platforms."
    dependsOn("jarWindows", "jarLinux", "jarMacos")
}
